### ISSUE TITLE
When try open in browser <ipaddress>:8081 appears a 404 page

### ISSUE THREAD

**Issue by DanilBorchevkin** [nickpasko/office_portal#1]
For get index page url have to be _ipaddress:8081/index/_

**Comment by nickpasko** [comment]
Known issue: no handler for root - "/"

**Comment by nickpasko** [comment]
Fixed by:
https://github.com/nickpasko/office_portal/pull/2/commits/9a12250c4efaf7ab3aef941ac34ee695bb455675
